name: 'Setup Poetry'
description: 'This action installs and setups the poetry in current environment'
runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - name: Setup Poetry
      run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
