name: Unit Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    name: Test on Python ${{ matrix.python_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python_version: ${{ matrix.python_version }}

    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    
    - name: Setup Poetry
      run: source $HOME/.poetry/env

    - name: install project dependencies
      run: make install

    - name: Run tests
      run: make test